version: '3'

services:

   mailhog:
      image: mailhog/mailhog:latest
      container_name: app-mailhog
      ports:
        - "8005:1025"
        - "8200:8025"
   app:
    image: laravel-www
    container_name: laravel-www
    build:
      context: .
      
    depends_on:
      - mailhog
      - db
    ports:
      - 8000:8000
    volumes:
      - ./:/app

   db:
    container_name: laravel-mysql
    image: mysql:latest
    ports:
      - 13306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: 
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_user@123        
